apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-1731318094888
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/jrichter/chbot:e59398f630b7976d2a7c22ed58b8f14dddae9d00@sha256:ed0f5f9643d3335293b4601ef827e7dee2fb2dcc57fb5a401261ab4a4d782e45 # use pre-built to bootstrap 
          name: app-inference
